#!/bin/sh

# build_website: Basic formating script for http://padb.pittman.co.uk
# $Revision$
# $Date$

set -e

echo Uploading website to http://padb.pittman.org.uk

FILES="index usage download email extensions modes full-report configuration"

TDIR=public

mkdir -p public

cp layout.css $TDIR
for FILE in $FILES
do
  echo Uploading $FILE
  cat header.html > $TDIR/$FILE.html
  cat $FILE.html >> $TDIR/$FILE.html
  cat footer.html >> $TDIR/$FILE.html
done

echo All done.
exit 0
