#!/bin/sh

# upload_website: Basic formating and upload script for http://padb.pittman.co.uk
# $Revision$
# $Date$

set -e

echo Uploading website to http://padb.pittman.org.uk

# Load the password from a non-public file ;)
. ~/padb-website-password.txt

FILES="index usage download email extensions modes full-report configuration"

ftp-upload --passive --host padb.pittman.org.uk -u padb@pittman.co.uk --password $PASSWORD layout.css

for FILE in $FILES
do
  echo Uploading $FILE
  TFILE=`mktemp`
  cat header.html > $TFILE
  cat $FILE.html >> $TFILE
  cat footer.html >> $TFILE
  ftp-upload --passive --host padb.pittman.org.uk -u padb@pittman.co.uk --password $PASSWORD --as $FILE.html $TFILE
  rm $TFILE
done

for PATCH in *.patch
do
  ftp-upload --passive --host padb.pittman.org.uk -u padb@pittman.co.uk --password $PASSWORD $PATCH
done

echo All done.
exit 0
